name: update_available_ios
description: iOS platform implementation of update_available
version: 2.3.0
repository: https://github.com/mateusfccp/update_available/tree/master/update_available_ios

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  meta: ^1.8.0
  package_info_plus: ^4.0.2
  pub_semver: ^2.1.4
  update_available_platform_interface: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: update_available
    platforms:
      ios:
        dartPluginClass: UpdateAvailableIosPlugin
